apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose -v convert
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.service: envoy
  name: envoy
spec:
  type: LoadBalancer
  ports:
    - name: "50213"
      port: 50213
      targetPort: 50213
  selector:
    io.kompose.service: envoy
status:
  loadBalancer: {}
