services:
  record-streams-uploader:
    restart: "no"
    entrypoint: [
      "echo",
      "Deleting old recordStream files.",
      "&&",
      "rm -rf /records/*",
      "&&",
      "echo",
      "This container is intentionally disabled by the EVM profile."
    ]
    command: []
  account-balances-uploader:
    restart: "no"
    entrypoint: [
      "echo",
      "Deleting old accountBalances files.",
      "&&",
      "rm -rf /balances/*",
      "&&",
      "echo",
      "This container is intentionally disabled by the EVM profile."
    ]
    command: []
  record-sidecar-uploader:
    restart: "no"
    entrypoint: [
      "echo",
      "Deleting old sidecars files.",
      "&&",
      "rm -rf /sidecar-files/*",
      "&&",
      "echo",
      "This container is intentionally disabled by the EVM profile."
    ]
    command: []
  minio:
    restart: "no"
    entrypoint: [ "echo", "This container is intentionally disabled by the EVM profile." ]
    command: []
  importer:
    volumes:
      - "${NETWORK_NODE_LOGS_ROOT_PATH}/accountBalances/:/node/streams/accountBalances/"
      - "${NETWORK_NODE_LOGS_ROOT_PATH}/recordStreams/:/node/streams/recordstreams/"
